/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinejunglaadmin.vistas;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author teban
 */
public class Confiteria extends javax.swing.JFrame {

    /**
     * Creates new form Confiteria
     */
    public Confiteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        Sp_Pal = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        Sp_gas = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        Sp_choc = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sp_gomi = new javax.swing.JSpinner();
        Sp_Nach = new javax.swing.JSpinner();
        Sp_sandwich = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_vendedor = new javax.swing.JLabel();
        txt_codcli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Box_metdpag = new javax.swing.JComboBox<>();
        bnt_pagar = new javax.swing.JButton();
        bnt_calcular = new javax.swing.JButton();
        CheckPalomitas = new javax.swing.JCheckBox();
        CheckSandwichs = new javax.swing.JCheckBox();
        CheckGaseosa = new javax.swing.JCheckBox();
        CheckChocolatina = new javax.swing.JCheckBox();
        CheckNachos = new javax.swing.JCheckBox();
        CheckGomitas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Palomitas");

        jLabel2.setText("Gaseosa");

        jLabel3.setText("Chocolatina");

        jLabel4.setText("Nachos");

        jLabel5.setText("Gomitas");

        jLabel6.setText("Sandwich");

        jLabel7.setText("Cod cliente:");

        jLabel8.setText("Cod vendedor:");

        txt_codcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codcliActionPerformed(evt);
            }
        });

        jLabel10.setText("Total");

        jLabel12.setText("Metodo de pago");

        Box_metdpag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Puntos" }));

        bnt_pagar.setText("Pagar");
        bnt_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_pagarActionPerformed(evt);
            }
        });

        bnt_calcular.setText("Calcular");

        CheckPalomitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPalomitasActionPerformed(evt);
            }
        });

        CheckSandwichs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSandwichsActionPerformed(evt);
            }
        });

        CheckChocolatina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckChocolatinaActionPerformed(evt);
            }
        });

        CheckGomitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckGomitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sp_Nach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sp_choc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sp_gas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(Sp_Pal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sp_sandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(75, 75, 75)
                            .addComponent(Sp_gomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckSandwichs)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckPalomitas)
                            .addComponent(CheckGaseosa)
                            .addComponent(CheckChocolatina)
                            .addComponent(CheckNachos)
                            .addComponent(CheckGomitas))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnt_calcular)
                                .addGap(87, 87, 87)
                                .addComponent(bnt_pagar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_codcli, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(lb_total))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lb_vendedor)
                                                .addComponent(Box_metdpag, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 102, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckSandwichs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_codcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lb_vendedor))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(Box_metdpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lb_total))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bnt_pagar)
                                    .addComponent(bnt_calcular)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Sp_Pal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckPalomitas))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Sp_gas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckGaseosa))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Sp_choc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckChocolatina))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Sp_Nach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckNachos))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckGomitas)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(Sp_gomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sp_sandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckPalomitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPalomitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckPalomitasActionPerformed

    private void CheckChocolatinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckChocolatinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckChocolatinaActionPerformed

    private void CheckGomitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckGomitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckGomitasActionPerformed

    private void CheckSandwichsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSandwichsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckSandwichsActionPerformed

    private void bnt_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_pagarActionPerformed

    private void txt_codcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codcliActionPerformed

    /**
     * @param args the command line arguments
     */

    public JComboBox<String> getBox_metdpag() {
        return Box_metdpag;
    }

    public void setBox_metdpag(JComboBox<String> Box_metdpag) {
        this.Box_metdpag = Box_metdpag;
    }

    public JCheckBox getCheckChocolatina() {
        return CheckChocolatina;
    }

    public void setCheckChocolatina(JCheckBox CheckChocolatina) {
        this.CheckChocolatina = CheckChocolatina;
    }

    public JCheckBox getCheckGaseosa() {
        return CheckGaseosa;
    }

    public void setCheckGaseosa(JCheckBox CheckGaseosa) {
        this.CheckGaseosa = CheckGaseosa;
    }

    public JCheckBox getCheckGomitas() {
        return CheckGomitas;
    }

    public void setCheckGomitas(JCheckBox CheckGomitas) {
        this.CheckGomitas = CheckGomitas;
    }

    public JCheckBox getCheckNachos() {
        return CheckNachos;
    }

    public void setCheckNachos(JCheckBox CheckNachos) {
        this.CheckNachos = CheckNachos;
    }

    public JCheckBox getCheckPalomitas() {
        return CheckPalomitas;
    }

    public void setCheckPalomitas(JCheckBox CheckPalomitas) {
        this.CheckPalomitas = CheckPalomitas;
    }

    public JCheckBox getCheckSandwichs() {
        return CheckSandwichs;
    }

    public void setCheckSandwichs(JCheckBox CheckSandwichs) {
        this.CheckSandwichs = CheckSandwichs;
    }

    public JSpinner getSp_Nach() {
        return Sp_Nach;
    }

    public void setSp_Nach(JSpinner Sp_Nach) {
        this.Sp_Nach = Sp_Nach;
    }

    public JSpinner getSp_Pal() {
        return Sp_Pal;
    }

    public void setSp_Pal(JSpinner Sp_Pal) {
        this.Sp_Pal = Sp_Pal;
    }

    public JSpinner getSp_choc() {
        return Sp_choc;
    }

    public void setSp_choc(JSpinner Sp_choc) {
        this.Sp_choc = Sp_choc;
    }

    public JSpinner getSp_gas() {
        return Sp_gas;
    }

    public void setSp_gas(JSpinner Sp_gas) {
        this.Sp_gas = Sp_gas;
    }

    public JSpinner getSp_gomi() {
        return Sp_gomi;
    }

    public void setSp_gomi(JSpinner Sp_gomi) {
        this.Sp_gomi = Sp_gomi;
    }

    public JSpinner getSp_sandwich() {
        return Sp_sandwich;
    }

    public void setSp_sandwich(JSpinner Sp_sandwich) {
        this.Sp_sandwich = Sp_sandwich;
    }

    public JButton getBnt_calcular() {
        return bnt_calcular;
    }

    public void setBnt_calcular(JButton bnt_calcular) {
        this.bnt_calcular = bnt_calcular;
    }

    public JButton getBnt_pagar() {
        return bnt_pagar;
    }

    public void setBnt_pagar(JButton bnt_pagar) {
        this.bnt_pagar = bnt_pagar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JSpinner getjSpinner1() {
        return jSpinner1;
    }

    public void setjSpinner1(JSpinner jSpinner1) {
        this.jSpinner1 = jSpinner1;
    }

    public JLabel getLb_total() {
        return lb_total;
    }

    public void setLb_total(JLabel lb_total) {
        this.lb_total = lb_total;
    }

    public JLabel getLb_vendedor() {
        return lb_vendedor;
    }

    public void setLb_vendedor(JLabel lb_vendedor) {
        this.lb_vendedor = lb_vendedor;
    }

    public JTextField getTxt_codcli() {
        return txt_codcli;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxt_codcli(JTextField txt_codcli) {
        this.txt_codcli = txt_codcli;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_metdpag;
    private javax.swing.JCheckBox CheckChocolatina;
    private javax.swing.JCheckBox CheckGaseosa;
    private javax.swing.JCheckBox CheckGomitas;
    private javax.swing.JCheckBox CheckNachos;
    private javax.swing.JCheckBox CheckPalomitas;
    private javax.swing.JCheckBox CheckSandwichs;
    private javax.swing.JSpinner Sp_Nach;
    private javax.swing.JSpinner Sp_Pal;
    private javax.swing.JSpinner Sp_choc;
    private javax.swing.JSpinner Sp_gas;
    private javax.swing.JSpinner Sp_gomi;
    private javax.swing.JSpinner Sp_sandwich;
    private javax.swing.JButton bnt_calcular;
    private javax.swing.JButton bnt_pagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lb_vendedor;
    private javax.swing.JTextField txt_codcli;
    // End of variables declaration//GEN-END:variables
}
