/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinejunglaadmin.vistas;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author teban
 */
public class Pane_admin extends javax.swing.JFrame {

    /**
     * Creates new form Pane_admin
     */
    public Pane_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Grupo_emp = new javax.swing.ButtonGroup();
        Grupo_prod = new javax.swing.ButtonGroup();
        Grupo_cli = new javax.swing.ButtonGroup();
        Grupo_fun = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        txt_idprod = new javax.swing.JTextField();
        txt_precioprod = new javax.swing.JTextField();
        txt_nombreprod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jrActualizarProd = new javax.swing.JRadioButton();
        jrBorrarProd = new javax.swing.JRadioButton();
        jrRegistarProd = new javax.swing.JRadioButton();
        bntRealizarProd = new javax.swing.JButton();
        bntBuscarProd = new javax.swing.JButton();
        txt_buscarProd = new javax.swing.JTextField();
        Box_filtroProd = new javax.swing.JComboBox<>();
        bntRefrescarProd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        txt_nombreurs = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bntActualizarusr = new javax.swing.JButton();
        bntBorrarusr = new javax.swing.JButton();
        bnt_Buscarusr = new javax.swing.JButton();
        txt_buscarusr = new javax.swing.JTextField();
        Box_filtrousr = new javax.swing.JComboBox<>();
        bntRegistarusr = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Box_tipousr = new javax.swing.JComboBox<>();
        bntRefrescarusr = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtFunciones = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lb_IDfun = new javax.swing.JLabel();
        txt_IDpelfun = new javax.swing.JTextField();
        txt_IDsalfun = new javax.swing.JTextField();
        txt_IDmulfun = new javax.swing.JTextField();
        txt_fechafun = new javax.swing.JTextField();
        rb_actualizarcli1 = new javax.swing.JRadioButton();
        rb_borrarcli1 = new javax.swing.JRadioButton();
        rb_registarcli1 = new javax.swing.JRadioButton();
        bntRealizarfun = new javax.swing.JButton();
        bntRefrescarfun = new javax.swing.JButton();
        bntBuscarFun = new javax.swing.JButton();
        txt_buscarFun = new javax.swing.JTextField();
        Box_filtroFun = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpleados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_fechaemp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Box_multiplexemp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_apellidoemp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cedulaemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nombreemp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cargoemp = new javax.swing.JTextField();
        txt_salarioemp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_telefonoemp = new javax.swing.JTextField();
        bntBuscar = new javax.swing.JButton();
        txt_buscaremp = new javax.swing.JTextField();
        Box_filtroemp = new javax.swing.JComboBox<>();
        bntRefrescaremp = new javax.swing.JButton();
        rb_actualizaremp = new javax.swing.JRadioButton();
        rb_borraremp = new javax.swing.JRadioButton();
        rd_registraremp = new javax.swing.JRadioButton();
        bntRealizaremp = new javax.swing.JButton();
        bntGenCod = new javax.swing.JButton();
        lb_cod = new javax.swing.JLabel();
        Limpiar_emp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        txt_nombrecli = new javax.swing.JTextField();
        txt_apellidocli = new javax.swing.JTextField();
        txt_emailcli = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        lb_apellido = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_resID = new javax.swing.JLabel();
        lb_puntos = new javax.swing.JLabel();
        lb_totalP = new javax.swing.JLabel();
        rb_actualizarcli = new javax.swing.JRadioButton();
        rb_borrarcli = new javax.swing.JRadioButton();
        rb_registarcli = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        bntBuscarcli = new javax.swing.JButton();
        txt_buscarcli = new javax.swing.JTextField();
        Box_filtroCli = new javax.swing.JComboBox<>();
        bntRefrescarcli = new javax.swing.JButton();
        bntLogout = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jtProductos);

        txt_idprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idprodActionPerformed(evt);
            }
        });

        txt_precioprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioprodActionPerformed(evt);
            }
        });

        txt_nombreprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreprodActionPerformed(evt);
            }
        });

        jLabel10.setText("ID");

        jLabel11.setText("Nombre");

        jLabel12.setText("Precio");

        Grupo_prod.add(jrActualizarProd);
        jrActualizarProd.setText("Actualizar");

        Grupo_prod.add(jrBorrarProd);
        jrBorrarProd.setText("Borrar");

        Grupo_prod.add(jrRegistarProd);
        jrRegistarProd.setText("Registar");

        bntRealizarProd.setText("Realizar");

        bntBuscarProd.setText("Buscar");
        bntBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarProdActionPerformed(evt);
            }
        });

        Box_filtroProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", " " }));

        bntRefrescarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRefrescarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Box_filtroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_buscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntBuscarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntRefrescarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntRealizarProd)
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jrActualizarProd)
                                .addGap(36, 36, 36)
                                .addComponent(jrBorrarProd)
                                .addGap(31, 31, 31)
                                .addComponent(jrRegistarProd)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idprod, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_precioprod, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrActualizarProd)
                            .addComponent(jrBorrarProd)
                            .addComponent(jrRegistarProd))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_nombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precioprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(59, 59, 59)
                        .addComponent(bntRealizarProd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Box_filtroProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_buscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bntBuscarProd))
                            .addComponent(bntRefrescarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Productos", jPanel1);

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Usuario", "Password", "last_session", "id_rango"
            }
        ));
        jScrollPane3.setViewportView(jtUsuarios);

        txt_nombreurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreursActionPerformed(evt);
            }
        });

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jLabel13.setText("Password");

        jLabel14.setText("Usuario");

        jLabel15.setText("Tipo de Usuario");

        bntActualizarusr.setText("Actualizar");
        bntActualizarusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntActualizarusrActionPerformed(evt);
            }
        });

        bntBorrarusr.setText("Borrar");
        bntBorrarusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBorrarusrActionPerformed(evt);
            }
        });

        bnt_Buscarusr.setText("Buscar");
        bnt_Buscarusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_BuscarusrActionPerformed(evt);
            }
        });

        txt_buscarusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarusrActionPerformed(evt);
            }
        });

        Box_filtrousr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuario", "id_rango" }));
        Box_filtrousr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_filtrousrActionPerformed(evt);
            }
        });

        bntRegistarusr.setText("Registrar");
        bntRegistarusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistarusrActionPerformed(evt);
            }
        });

        jLabel16.setText("<html>Si desea registrar un nuevo usuario este debe estar registrado en la tabla de empleados y el usuario se debe crear con su codigo generado :</html>");

        Box_tipousr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        bntRefrescarusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRefrescarusrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(bnt_Buscarusr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntRefrescarusr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 363, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntRegistarusr)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(bntBorrarusr)
                        .addGap(41, 41, 41)
                        .addComponent(bntActualizarusr)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Box_tipousr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(Box_filtrousr, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_buscarusr, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane3))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nombreurs, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(txt_password))
                    .addGap(97, 97, 97)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(Box_tipousr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntRefrescarusr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntActualizarusr)
                            .addComponent(bntBorrarusr))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(bntRegistarusr)
                                .addGap(32, 32, 32)))
                        .addGap(61, 61, 61)
                        .addComponent(bnt_Buscarusr)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_buscarusr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box_filtrousr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(txt_nombreurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addComponent(jLabel15)
                            .addGap(337, 337, 337)))
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Usuarios", jPanel3);

        jtFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Pelicula", "Sala", "Multiplex","Fecha"
            }
        ));
        jScrollPane4.setViewportView(jtFunciones);

        jLabel17.setText("ID");

        jLabel18.setText("ID Pelicula");

        jLabel19.setText("ID Sala");

        jLabel20.setText("ID multiplex");

        jLabel21.setText("Hora Inicio");

        txt_IDpelfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDpelfunActionPerformed(evt);
            }
        });

        txt_IDmulfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDmulfunActionPerformed(evt);
            }
        });

        txt_fechafun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechafunActionPerformed(evt);
            }
        });

        Grupo_fun.add(rb_actualizarcli1);
        rb_actualizarcli1.setText("Actualizar");

        Grupo_fun.add(rb_borrarcli1);
        rb_borrarcli1.setText("Borrar");

        Grupo_fun.add(rb_registarcli1);
        rb_registarcli1.setText("Registar");

        bntRealizarfun.setText("Realizar");

        bntRefrescarfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRefrescarfunActionPerformed(evt);
            }
        });

        bntBuscarFun.setText("Buscar");
        bntBuscarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarFunActionPerformed(evt);
            }
        });

        txt_buscarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarFunActionPerformed(evt);
            }
        });

        Box_filtroFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID" }));
        Box_filtroFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_filtroFunActionPerformed(evt);
            }
        });

        jLabel23.setText("Formato para actualizar: \"yyyy-MM-dd HH:mm:ss\"");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Box_filtroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntBuscarFun)
                        .addGap(18, 18, 18)
                        .addComponent(bntRefrescarfun, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel21)))))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_IDsalfun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_IDpelfun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_IDmulfun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fechafun, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel17)
                                .addGap(87, 87, 87)
                                .addComponent(lb_IDfun))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel23))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(rb_actualizarcli1)
                                        .addGap(44, 44, 44)
                                        .addComponent(rb_borrarcli1))
                                    .addComponent(bntRealizarfun))
                                .addGap(44, 44, 44)
                                .addComponent(rb_registarcli1)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_IDfun)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_IDpelfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_IDsalfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_IDmulfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_fechafun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_actualizarcli1)
                            .addComponent(rb_borrarcli1)
                            .addComponent(rb_registarcli1))
                        .addGap(33, 33, 33)
                        .addComponent(bntRealizarfun)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscarFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntBuscarFun)
                        .addComponent(Box_filtroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bntRefrescarfun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funciones", jPanel5);

        jtEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cod_emp", "Nombre", "Apellido","Cargo","Multiplex_ID"
            }
        ));
        jScrollPane1.setViewportView(jtEmpleados);

        jLabel7.setText("Fecha de incio");

        jLabel8.setText("Salario");

        jLabel9.setText("Multiplex");

        Box_multiplexemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titan", "Unicentro", "Plaza Central", "Gran Estacion", "Embajador", "Las Americas" }));
        Box_multiplexemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_multiplexempActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod_emp");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Cedula");

        jLabel5.setText("Cargo");

        jLabel6.setText("Telefono");

        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        txt_buscaremp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarempActionPerformed(evt);
            }
        });

        Box_filtroemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cod_emp", "Multiplex_ID", "cedula" }));
        Box_filtroemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_filtroempActionPerformed(evt);
            }
        });

        bntRefrescaremp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRefrescarempActionPerformed(evt);
            }
        });

        Grupo_emp.add(rb_actualizaremp);
        rb_actualizaremp.setText("Actualizar");

        Grupo_emp.add(rb_borraremp);
        rb_borraremp.setText("Borrar");

        Grupo_emp.add(rd_registraremp);
        rd_registraremp.setText("Registrar");

        bntRealizaremp.setText("Realizar");

        bntGenCod.setText("Generar");

        Limpiar_emp.setText("Limpiar");
        Limpiar_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_empActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Box_filtroemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscaremp, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bntBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntRefrescaremp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rb_actualizaremp)
                        .addGap(33, 33, 33)
                        .addComponent(rb_borraremp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(rd_registraremp)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lb_cod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntGenCod))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_salarioemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_fechaemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telefonoemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cargoemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cedulaemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_apellidoemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombreemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Box_multiplexemp, 0, 205, Short.MAX_VALUE))
                                .addGap(30, 30, 30)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Limpiar_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntRealizaremp)
                        .addGap(71, 71, 71))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_actualizaremp)
                    .addComponent(rb_borraremp)
                    .addComponent(rd_registraremp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombreemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_apellidoemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cedulaemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_cargoemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_telefonoemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_fechaemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_salarioemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Box_multiplexemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bntGenCod)
                    .addComponent(lb_cod))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRealizaremp)
                    .addComponent(Limpiar_emp))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscaremp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Box_filtroemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntBuscar))
                    .addComponent(bntRefrescaremp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel2);

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] { },
            new String [] {
                "ID", "Nombre", "Apellido", "Email","Puntos"
            }
        ));
        jScrollPane5.setViewportView(jtClientes);

        txt_nombrecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombrecliActionPerformed(evt);
            }
        });

        txt_emailcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailcliActionPerformed(evt);
            }
        });

        lb_nombre.setText("Nombre");

        lb_apellido.setText("Apellido");

        lb_email.setText("Email");

        lb_id.setText("ID");

        lb_puntos.setText("Puntos acum");

        Grupo_cli.add(rb_actualizarcli);
        rb_actualizarcli.setText("Actualizar");

        Grupo_cli.add(rb_borrarcli);
        rb_borrarcli.setText("Borrar");

        Grupo_cli.add(rb_registarcli);
        rb_registarcli.setText("Registar");

        jButton1.setText("Realizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bntBuscarcli.setText("Buscar");
        bntBuscarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarcliActionPerformed(evt);
            }
        });

        Box_filtroCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", " " }));
        Box_filtroCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_filtroCliActionPerformed(evt);
            }
        });

        bntRefrescarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRefrescarcliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Box_filtroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntBuscarcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntRefrescarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rb_actualizarcli)
                        .addGap(46, 46, 46)
                        .addComponent(rb_borrarcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(rb_registarcli))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nombre)
                            .addComponent(lb_apellido)
                            .addComponent(lb_email)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lb_id)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombrecli)
                                    .addComponent(txt_emailcli)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_apellidocli)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lb_resID, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lb_puntos)
                        .addGap(18, 18, 18)
                        .addComponent(lb_totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_borrarcli, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rb_actualizarcli)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rb_registarcli)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nombre))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_apellidocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_apellido))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_emailcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_email))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_id)
                            .addComponent(lb_resID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lb_puntos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lb_totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 31, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Box_filtroCli)
                    .addComponent(txt_buscarcli)
                    .addComponent(bntBuscarcli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntRefrescarcli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Clientes", jPanel4);

        bntLogout.setText("Salir");
        bntLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntLogout)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bntLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    private void bntLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntLogoutActionPerformed

    private void bntRefrescarempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRefrescarempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRefrescarempActionPerformed

    private void Box_filtroempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_filtroempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_filtroempActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void Box_multiplexempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_multiplexempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_multiplexempActionPerformed

    private void bntRegistarusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistarusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRegistarusrActionPerformed

    private void Box_filtrousrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_filtrousrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_filtrousrActionPerformed

    private void bnt_BuscarusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_BuscarusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_BuscarusrActionPerformed

    private void bntBorrarusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBorrarusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBorrarusrActionPerformed

    private void bntActualizarusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntActualizarusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntActualizarusrActionPerformed

    private void txt_buscarempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarempActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_nombreursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreursActionPerformed

    private void bntRefrescarfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRefrescarfunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRefrescarfunActionPerformed

    private void bntBuscarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBuscarFunActionPerformed

    private void Box_filtroFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_filtroFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_filtroFunActionPerformed

    private void txt_buscarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarFunActionPerformed

    private void txt_IDmulfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDmulfunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDmulfunActionPerformed

    private void txt_IDpelfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDpelfunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDpelfunActionPerformed

    private void txt_fechafunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechafunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechafunActionPerformed

    private void bntRefrescarusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRefrescarusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRefrescarusrActionPerformed

    private void bntRefrescarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRefrescarcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRefrescarcliActionPerformed

    private void Box_filtroCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_filtroCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_filtroCliActionPerformed

    private void bntBuscarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBuscarcliActionPerformed

    private void txt_emailcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailcliActionPerformed

    private void txt_nombrecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombrecliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombrecliActionPerformed

    private void bntRefrescarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRefrescarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRefrescarProdActionPerformed

    private void bntBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBuscarProdActionPerformed

    private void txt_nombreprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreprodActionPerformed

    private void txt_precioprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioprodActionPerformed

    private void txt_buscarusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarusrActionPerformed

    private void txt_idprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idprodActionPerformed

    private void Limpiar_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Limpiar_empActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    public JComboBox<String> getBox_filtroCli() {
        return Box_filtroCli;
    }

    public void setBox_filtroCli(JComboBox<String> Box_filtroCli) {
        this.Box_filtroCli = Box_filtroCli;
    }

    public JComboBox<String> getBox_filtroFun() {
        return Box_filtroFun;
    }

    public void setBox_filtroFun(JComboBox<String> Box_filtroFun) {
        this.Box_filtroFun = Box_filtroFun;
    }

    public JComboBox<String> getBox_filtroProd() {
        return Box_filtroProd;
    }

    public void setBox_filtroProd(JComboBox<String> Box_filtroProd) {
        this.Box_filtroProd = Box_filtroProd;
    }

    public JComboBox<String> getBox_filtroemp() {
        return Box_filtroemp;
    }

    public void setBox_filtroemp(JComboBox<String> Box_filtroemp) {
        this.Box_filtroemp = Box_filtroemp;
    }

    public JComboBox<String> getBox_filtrousr() {
        return Box_filtrousr;
    }

    public void setBox_filtrousr(JComboBox<String> Box_filtrousr) {
        this.Box_filtrousr = Box_filtrousr;
    }

    public JComboBox<String> getBox_multiplexemp() {
        return Box_multiplexemp;
    }

    public void setBox_multiplexemp(JComboBox<String> Box_multiplexemp) {
        this.Box_multiplexemp = Box_multiplexemp;
    }

    public JComboBox<String> getBox_tipousr() {
        return Box_tipousr;
    }

    public void setBox_tipousr(JComboBox<String> Box_tipousr) {
        this.Box_tipousr = Box_tipousr;
    }

    public ButtonGroup getGrupo_emp() {
        return Grupo_emp;
    }

    public void setGrupo_emp(ButtonGroup Grupo_emp) {
        this.Grupo_emp = Grupo_emp;
    }

    public ButtonGroup getGrupo_prod() {
        return Grupo_prod;
    }

    public void setGrupo_prod(ButtonGroup Grupo_prod) {
        this.Grupo_prod = Grupo_prod;
    }

    public JButton getBntActualizarusr() {
        return bntActualizarusr;
    }

    public void setBntActualizarusr(JButton bntActualizarusr) {
        this.bntActualizarusr = bntActualizarusr;
    }

    public JButton getBntBorrarusr() {
        return bntBorrarusr;
    }

    public void setBntBorrarusr(JButton bntBorrarusr) {
        this.bntBorrarusr = bntBorrarusr;
    }

    public JButton getBntBuscar() {
        return bntBuscar;
    }

    public void setBntBuscar(JButton bntBuscar) {
        this.bntBuscar = bntBuscar;
    }

    public JButton getBntBuscarFun() {
        return bntBuscarFun;
    }

    public void setBntBuscarFun(JButton bntBuscarFun) {
        this.bntBuscarFun = bntBuscarFun;
    }

    public JButton getBntBuscarProd() {
        return bntBuscarProd;
    }

    public void setBntBuscarProd(JButton bntBuscarProd) {
        this.bntBuscarProd = bntBuscarProd;
    }

    public JButton getBntBuscarcli() {
        return bntBuscarcli;
    }

    public void setBntBuscarcli(JButton bntBuscarcli) {
        this.bntBuscarcli = bntBuscarcli;
    }

    public JButton getBntGenCod() {
        return bntGenCod;
    }

    public void setBntGenCod(JButton bntGenCod) {
        this.bntGenCod = bntGenCod;
    }

    public JButton getBntLogout() {
        return bntLogout;
    }

    public void setBntLogout(JButton bntLogout) {
        this.bntLogout = bntLogout;
    }

    public JButton getBntRealizarProd() {
        return bntRealizarProd;
    }

    public void setBntRealizarProd(JButton bntRealizarProd) {
        this.bntRealizarProd = bntRealizarProd;
    }

    public JButton getBntRealizaremp() {
        return bntRealizaremp;
    }

    public void setBntRealizaremp(JButton bntRealizaremp) {
        this.bntRealizaremp = bntRealizaremp;
    }

    public JButton getBntRealizarfun() {
        return bntRealizarfun;
    }

    public void setBntRealizarfun(JButton bntRealizarfun) {
        this.bntRealizarfun = bntRealizarfun;
    }

    public JButton getBntRefrescarProd() {
        return bntRefrescarProd;
    }

    public void setBntRefrescarProd(JButton bntRefrescarProd) {
        this.bntRefrescarProd = bntRefrescarProd;
    }

    public JButton getBntRefrescarcli() {
        return bntRefrescarcli;
    }

    public void setBntRefrescarcli(JButton bntRefrescarcli) {
        this.bntRefrescarcli = bntRefrescarcli;
    }

    public JButton getBntRefrescaremp() {
        return bntRefrescaremp;
    }

    public void setBntRefrescaremp(JButton bntRefrescaremp) {
        this.bntRefrescaremp = bntRefrescaremp;
    }

    public JButton getBntRefrescarfun() {
        return bntRefrescarfun;
    }

    public void setBntRefrescarfun(JButton bntRefrescarfun) {
        this.bntRefrescarfun = bntRefrescarfun;
    }

    public JButton getBntRefrescarusr() {
        return bntRefrescarusr;
    }

    public void setBntRefrescarusr(JButton bntRefrescarusr) {
        this.bntRefrescarusr = bntRefrescarusr;
    }

    public JButton getBntRegistarusr() {
        return bntRegistarusr;
    }

    public void setBntRegistarusr(JButton bntRegistarusr) {
        this.bntRegistarusr = bntRegistarusr;
    }

    public JButton getBnt_Buscarusr() {
        return bnt_Buscarusr;
    }

    public void setBnt_Buscarusr(JButton bnt_Buscarusr) {
        this.bnt_Buscarusr = bnt_Buscarusr;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPopupMenu getjPopupMenu1() {
        return jPopupMenu1;
    }

    public void setjPopupMenu1(JPopupMenu jPopupMenu1) {
        this.jPopupMenu1 = jPopupMenu1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public void setjScrollPane5(JScrollPane jScrollPane5) {
        this.jScrollPane5 = jScrollPane5;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JRadioButton getJrActualizarProd() {
        return jrActualizarProd;
    }

    public void setJrActualizarProd(JRadioButton jrActualizarProd) {
        this.jrActualizarProd = jrActualizarProd;
    }

    public JRadioButton getJrBorrarProd() {
        return jrBorrarProd;
    }

    public void setJrBorrarProd(JRadioButton jrBorrarProd) {
        this.jrBorrarProd = jrBorrarProd;
    }

    public JRadioButton getJrRegistarProd() {
        return jrRegistarProd;
    }

    public void setJrRegistarProd(JRadioButton jrRegistarProd) {
        this.jrRegistarProd = jrRegistarProd;
    }

    public JTable getJtClientes() {
        return jtClientes;
    }

    public void setJtClientes(JTable jtClientes) {
        this.jtClientes = jtClientes;
    }

    public JTable getJtEmpleados() {
        return jtEmpleados;
    }

    public void setJtEmpleados(JTable jtEmpleados) {
        this.jtEmpleados = jtEmpleados;
    }

    public JTable getJtFunciones() {
        return jtFunciones;
    }

    public void setJtFunciones(JTable jtFunciones) {
        this.jtFunciones = jtFunciones;
    }

    public JTable getJtProductos() {
        return jtProductos;
    }

    public void setJtProductos(JTable jtProductos) {
        this.jtProductos = jtProductos;
    }

    public JTable getJtUsuarios() {
        return jtUsuarios;
    }

    public void setJtUsuarios(JTable jtUsuarios) {
        this.jtUsuarios = jtUsuarios;
    }

    public JLabel getLb_IDfun() {
        return lb_IDfun;
    }

    public void setLb_IDfun(JLabel lb_IDfun) {
        this.lb_IDfun = lb_IDfun;
    }

    public JLabel getLb_apellido() {
        return lb_apellido;
    }

    public void setLb_apellido(JLabel lb_apellido) {
        this.lb_apellido = lb_apellido;
    }

    public JLabel getLb_cod() {
        return lb_cod;
    }

    public void setLb_cod(JLabel lb_cod) {
        this.lb_cod = lb_cod;
    }

    public JLabel getLb_email() {
        return lb_email;
    }

    public void setLb_email(JLabel lb_email) {
        this.lb_email = lb_email;
    }

    public JLabel getLb_id() {
        return lb_id;
    }

    public void setLb_id(JLabel lb_id) {
        this.lb_id = lb_id;
    }

    public JLabel getLb_nombre() {
        return lb_nombre;
    }

    public void setLb_nombre(JLabel lb_nombre) {
        this.lb_nombre = lb_nombre;
    }

    public JLabel getLb_puntos() {
        return lb_puntos;
    }

    public void setLb_puntos(JLabel lb_puntos) {
        this.lb_puntos = lb_puntos;
    }

    public JLabel getLb_resID() {
        return lb_resID;
    }

    public void setLb_resID(JLabel lb_resID) {
        this.lb_resID = lb_resID;
    }

    public JLabel getLb_totalP() {
        return lb_totalP;
    }

    public void setLb_totalP(JLabel lb_totalP) {
        this.lb_totalP = lb_totalP;
    }

    public JRadioButton getRb_actualizarcli() {
        return rb_actualizarcli;
    }

    public void setRb_actualizarcli(JRadioButton rb_actualizarcli) {
        this.rb_actualizarcli = rb_actualizarcli;
    }

    public JRadioButton getRb_actualizarcli1() {
        return rb_actualizarcli1;
    }

    public void setRb_actualizarcli1(JRadioButton rb_actualizarcli1) {
        this.rb_actualizarcli1 = rb_actualizarcli1;
    }

    public JRadioButton getRb_actualizaremp() {
        return rb_actualizaremp;
    }

    public void setRb_actualizaremp(JRadioButton rb_actualizaremp) {
        this.rb_actualizaremp = rb_actualizaremp;
    }

    public JRadioButton getRb_borrarcli() {
        return rb_borrarcli;
    }

    public void setRb_borrarcli(JRadioButton rb_borrarcli) {
        this.rb_borrarcli = rb_borrarcli;
    }

    public JRadioButton getRb_borrarcli1() {
        return rb_borrarcli1;
    }

    public void setRb_borrarcli1(JRadioButton rb_borrarcli1) {
        this.rb_borrarcli1 = rb_borrarcli1;
    }

    public JRadioButton getRb_borraremp() {
        return rb_borraremp;
    }

    public void setRb_borraremp(JRadioButton rb_borraremp) {
        this.rb_borraremp = rb_borraremp;
    }

    public JRadioButton getRb_registarcli() {
        return rb_registarcli;
    }

    public void setRb_registarcli(JRadioButton rb_registarcli) {
        this.rb_registarcli = rb_registarcli;
    }

    public JRadioButton getRb_registarcli1() {
        return rb_registarcli1;
    }

    public void setRb_registarcli1(JRadioButton rb_registarcli1) {
        this.rb_registarcli1 = rb_registarcli1;
    }

    public JRadioButton getRd_registraremp() {
        return rd_registraremp;
    }

    public void setRd_registraremp(JRadioButton rd_registraremp) {
        this.rd_registraremp = rd_registraremp;
    }

    public JTextField getTxt_IDmulfun() {
        return txt_IDmulfun;
    }

    public void setTxt_IDmulfun(JTextField txt_IDmulfun) {
        this.txt_IDmulfun = txt_IDmulfun;
    }

    public JTextField getTxt_IDpelfun() {
        return txt_IDpelfun;
    }

    public void setTxt_IDpelfun(JTextField txt_IDpelfun) {
        this.txt_IDpelfun = txt_IDpelfun;
    }

    public JTextField getTxt_IDsalfun() {
        return txt_IDsalfun;
    }

    public void setTxt_IDsalfun(JTextField txt_IDsalfun) {
        this.txt_IDsalfun = txt_IDsalfun;
    }

    public JTextField getTxt_apellidocli() {
        return txt_apellidocli;
    }

    public void setTxt_apellidocli(JTextField txt_apellidocli) {
        this.txt_apellidocli = txt_apellidocli;
    }

    public JTextField getTxt_apellidoemp() {
        return txt_apellidoemp;
    }

    public void setTxt_apellidoemp(JTextField txt_apellidoemp) {
        this.txt_apellidoemp = txt_apellidoemp;
    }

    public JTextField getTxt_buscarFun() {
        return txt_buscarFun;
    }

    public void setTxt_buscarFun(JTextField txt_buscarFun) {
        this.txt_buscarFun = txt_buscarFun;
    }

    public JTextField getTxt_buscarProd() {
        return txt_buscarProd;
    }

    public void setTxt_buscarProd(JTextField txt_buscarProd) {
        this.txt_buscarProd = txt_buscarProd;
    }

    public JTextField getTxt_buscarcli() {
        return txt_buscarcli;
    }

    public void setTxt_buscarcli(JTextField txt_buscarcli) {
        this.txt_buscarcli = txt_buscarcli;
    }

    public JTextField getTxt_buscaremp() {
        return txt_buscaremp;
    }

    public void setTxt_buscaremp(JTextField txt_buscaremp) {
        this.txt_buscaremp = txt_buscaremp;
    }

    public JTextField getTxt_buscarusr() {
        return txt_buscarusr;
    }

    public void setTxt_buscarusr(JTextField txt_buscarusr) {
        this.txt_buscarusr = txt_buscarusr;
    }

    public JTextField getTxt_cargoemp() {
        return txt_cargoemp;
    }

    public void setTxt_cargoemp(JTextField txt_cargoemp) {
        this.txt_cargoemp = txt_cargoemp;
    }

    public JTextField getTxt_cedulaemp() {
        return txt_cedulaemp;
    }

    public void setTxt_cedulaemp(JTextField txt_cedulaemp) {
        this.txt_cedulaemp = txt_cedulaemp;
    }

    public JTextField getTxt_emailcli() {
        return txt_emailcli;
    }

    public void setTxt_emailcli(JTextField txt_emailcli) {
        this.txt_emailcli = txt_emailcli;
    }

    public JTextField getTxt_fechaemp() {
        return txt_fechaemp;
    }

    public void setTxt_fechaemp(JTextField txt_fechaemp) {
        this.txt_fechaemp = txt_fechaemp;
    }

    public JTextField getTxt_fechafun() {
        return txt_fechafun;
    }

    public void setTxt_fechafun(JTextField txt_fechafun) {
        this.txt_fechafun = txt_fechafun;
    }

    public JTextField getTxt_idprod() {
        return txt_idprod;
    }

    public void setTxt_idprod(JTextField txt_idprod) {
        this.txt_idprod = txt_idprod;
    }

    public JTextField getTxt_nombrecli() {
        return txt_nombrecli;
    }

    public void setTxt_nombrecli(JTextField txt_nombrecli) {
        this.txt_nombrecli = txt_nombrecli;
    }

    public JTextField getTxt_nombreemp() {
        return txt_nombreemp;
    }

    public void setTxt_nombreemp(JTextField txt_nombreemp) {
        this.txt_nombreemp = txt_nombreemp;
    }

    public JTextField getTxt_nombreprod() {
        return txt_nombreprod;
    }

    public void setTxt_nombreprod(JTextField txt_nombreprod) {
        this.txt_nombreprod = txt_nombreprod;
    }

    public JTextField getTxt_nombreurs() {
        return txt_nombreurs;
    }

    public void setTxt_nombreurs(JTextField txt_nombreurs) {
        this.txt_nombreurs = txt_nombreurs;
    }

    public JTextField getTxt_password() {
        return txt_password;
    }

    public void setTxt_password(JTextField txt_password) {
        this.txt_password = txt_password;
    }

    public JTextField getTxt_precioprod() {
        return txt_precioprod;
    }

    public void setTxt_precioprod(JTextField txt_precioprod) {
        this.txt_precioprod = txt_precioprod;
    }

    public JTextField getTxt_salarioemp() {
        return txt_salarioemp;
    }

    public void setTxt_salarioemp(JTextField txt_salarioemp) {
        this.txt_salarioemp = txt_salarioemp;
    }

    public JTextField getTxt_telefonoemp() {
        return txt_telefonoemp;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxt_telefonoemp(JTextField txt_telefonoemp) {
        this.txt_telefonoemp = txt_telefonoemp;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_filtroCli;
    private javax.swing.JComboBox<String> Box_filtroFun;
    private javax.swing.JComboBox<String> Box_filtroProd;
    private javax.swing.JComboBox<String> Box_filtroemp;
    private javax.swing.JComboBox<String> Box_filtrousr;
    private javax.swing.JComboBox<String> Box_multiplexemp;
    private javax.swing.JComboBox<String> Box_tipousr;
    private javax.swing.ButtonGroup Grupo_cli;
    private javax.swing.ButtonGroup Grupo_emp;
    private javax.swing.ButtonGroup Grupo_fun;
    private javax.swing.ButtonGroup Grupo_prod;
    private javax.swing.JButton Limpiar_emp;
    private javax.swing.JButton bntActualizarusr;
    private javax.swing.JButton bntBorrarusr;
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton bntBuscarFun;
    private javax.swing.JButton bntBuscarProd;
    private javax.swing.JButton bntBuscarcli;
    private javax.swing.JButton bntGenCod;
    private javax.swing.JButton bntLogout;
    private javax.swing.JButton bntRealizarProd;
    private javax.swing.JButton bntRealizaremp;
    private javax.swing.JButton bntRealizarfun;
    private javax.swing.JButton bntRefrescarProd;
    private javax.swing.JButton bntRefrescarcli;
    private javax.swing.JButton bntRefrescaremp;
    private javax.swing.JButton bntRefrescarfun;
    private javax.swing.JButton bntRefrescarusr;
    private javax.swing.JButton bntRegistarusr;
    private javax.swing.JButton bnt_Buscarusr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jrActualizarProd;
    private javax.swing.JRadioButton jrBorrarProd;
    private javax.swing.JRadioButton jrRegistarProd;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTable jtEmpleados;
    private javax.swing.JTable jtFunciones;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JLabel lb_IDfun;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_cod;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_puntos;
    private javax.swing.JLabel lb_resID;
    private javax.swing.JLabel lb_totalP;
    private javax.swing.JRadioButton rb_actualizarcli;
    private javax.swing.JRadioButton rb_actualizarcli1;
    private javax.swing.JRadioButton rb_actualizaremp;
    private javax.swing.JRadioButton rb_borrarcli;
    private javax.swing.JRadioButton rb_borrarcli1;
    private javax.swing.JRadioButton rb_borraremp;
    private javax.swing.JRadioButton rb_registarcli;
    private javax.swing.JRadioButton rb_registarcli1;
    private javax.swing.JRadioButton rd_registraremp;
    private javax.swing.JTextField txt_IDmulfun;
    private javax.swing.JTextField txt_IDpelfun;
    private javax.swing.JTextField txt_IDsalfun;
    private javax.swing.JTextField txt_apellidocli;
    private javax.swing.JTextField txt_apellidoemp;
    private javax.swing.JTextField txt_buscarFun;
    private javax.swing.JTextField txt_buscarProd;
    private javax.swing.JTextField txt_buscarcli;
    private javax.swing.JTextField txt_buscaremp;
    private javax.swing.JTextField txt_buscarusr;
    private javax.swing.JTextField txt_cargoemp;
    private javax.swing.JTextField txt_cedulaemp;
    private javax.swing.JTextField txt_emailcli;
    private javax.swing.JTextField txt_fechaemp;
    private javax.swing.JTextField txt_fechafun;
    private javax.swing.JTextField txt_idprod;
    private javax.swing.JTextField txt_nombrecli;
    private javax.swing.JTextField txt_nombreemp;
    private javax.swing.JTextField txt_nombreprod;
    private javax.swing.JTextField txt_nombreurs;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_precioprod;
    private javax.swing.JTextField txt_salarioemp;
    private javax.swing.JTextField txt_telefonoemp;
    // End of variables declaration//GEN-END:variables
}
