/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinejunglaadmin.vistas;

import cinejunglaadmin.Conector;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author teban
 */
public class Taquilla extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Taquilla() {
        initComponents();
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conector con = new Conector();
        Connection conn = con.conexion();
        
        try {
            String query = "Select Nombre from multiplex";
            ps = conn.prepareStatement(query);
            rs = ps.executeQuery();
            
            while(rs.next()){
            
            getBox_mul().addItem(rs.getString("Nombre"));
                
            }
            
            String query2 = "Select Nombre from peliculas";
            ps = conn.prepareStatement(query2);
            rs = ps.executeQuery();
            
            while(rs.next()){
            
            getBox_pel().addItem(rs.getString("Nombre"));
                
            }
            
        } catch (Exception e) {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Box_mul = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Box_pel = new javax.swing.JComboBox<>();
        Box_func = new javax.swing.JComboBox<>();
        txt_fila = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bnt_ver = new javax.swing.JButton();
        lb_disp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bnt_Pago = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        Cod_cli = new javax.swing.JLabel();
        txt_codclii = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Multiplex");

        jLabel2.setText("Pelicula");

        jLabel3.setText("Asientos");

        jLabel4.setText("Funciones");

        Box_pel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_pelActionPerformed(evt);
            }
        });

        Box_func.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Box_funcItemStateChanged(evt);
            }
        });
        Box_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_funcActionPerformed(evt);
            }
        });

        jLabel5.setText("Los asientos en las filas E y F son Preferencial");

        bnt_ver.setText("Verificar");
        bnt_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_verActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        bnt_Pago.setText("Pagar");
        bnt_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_PagoActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Debito", "Puntos" }));

        jLabel8.setText("Medio de pago");

        Cod_cli.setText("Cod cli");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Box_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Box_pel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(100, 100, 100)
                                            .addComponent(Box_mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(20, 20, 20))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(bnt_ver)
                                .addGap(18, 18, 18)
                                .addComponent(lb_disp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Cod_cli)
                                .addGap(18, 18, 18)
                                .addComponent(txt_codclii, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bnt_Pago)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(67, 67, 67)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(79, 79, 79)
                                    .addComponent(jLabel7))))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Box_mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cod_cli)
                    .addComponent(txt_codclii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Box_pel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Box_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(bnt_ver)
                        .addComponent(lb_disp)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(bnt_Pago)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box_pelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_pelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_pelActionPerformed

    private void bnt_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_verActionPerformed
        
    }//GEN-LAST:event_bnt_verActionPerformed

    private void bnt_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_PagoActionPerformed
      
        
    }//GEN-LAST:event_bnt_PagoActionPerformed

    private void Box_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_funcActionPerformed
       
    }//GEN-LAST:event_Box_funcActionPerformed

    private void Box_funcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Box_funcItemStateChanged
        
    }//GEN-LAST:event_Box_funcItemStateChanged

    public JLabel getCod_cli() {
        return Cod_cli;
    }

    public void setCod_cli(JLabel Cod_cli) {
        this.Cod_cli = Cod_cli;
    }

    public JButton getBnt_Pago() {
        return bnt_Pago;
    }

    public void setBnt_Pago(JButton bnt_Pago) {
        this.bnt_Pago = bnt_Pago;
    }

    public JTextField getTxt_codclii() {
        return txt_codclii;
    }

    public void setTxt_codclii(JTextField txt_codclii) {
        this.txt_codclii = txt_codclii;
    }

    /**
     * @param args the command line arguments
     */
    

    public JButton getBnt_ver() {
        return bnt_ver;
    }

    public void setBnt_ver(JButton bnt_ver) {
        this.bnt_ver = bnt_ver;
    }

    public JTextField getTxt_fila() {
        return txt_fila;
    }

    public void setTxt_fila(JTextField txt_fila) {
        this.txt_fila = txt_fila;
    }

    public JTextField getTxt_numero() {
        return txt_numero;
    }

    public void setTxt_numero(JTextField txt_numero) {
        this.txt_numero = txt_numero;
    }

    public JComboBox<String> getBox_func() {
        return Box_func;
    }

    public void setBox_func(JComboBox<String> Box_func) {
        this.Box_func = Box_func;
    }

    public JComboBox<String> getBox_mul() {
        return Box_mul;
    }

    public void setBox_mul(JComboBox<String> Box_mul) {
        this.Box_mul = Box_mul;
    }

    public JComboBox<String> getBox_pel() {
        return Box_pel;
    }

    public void setBox_pel(JComboBox<String> Box_pel) {
        this.Box_pel = Box_pel;
    }

    public JButton getjButton1() {
        return bnt_ver;
    }

    public void setjButton1(JButton jButton1) {
        this.bnt_ver = jButton1;
    }

    public JButton getjButton2() {
        return bnt_Pago;
    }

    public void setjButton2(JButton jButton2) {
        this.bnt_Pago = jButton2;
    }

    public JComboBox<String> getjComboBox4() {
        return jComboBox4;
    }

    public void setjComboBox4(JComboBox<String> jComboBox4) {
        this.jComboBox4 = jComboBox4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getLb_disp() {
        return lb_disp;
    }

    public void setLb_disp(JLabel lb_disp) {
        this.lb_disp = lb_disp;
    }

    public JTextField getTxt_asientos() {
        return txt_fila;
    }

    public void setTxt_asientos(JTextField txt_asientos) {
        this.txt_fila = txt_asientos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_func;
    private javax.swing.JComboBox<String> Box_mul;
    private javax.swing.JComboBox<String> Box_pel;
    private javax.swing.JLabel Cod_cli;
    private javax.swing.JButton bnt_Pago;
    private javax.swing.JButton bnt_ver;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_disp;
    private javax.swing.JTextField txt_codclii;
    private javax.swing.JTextField txt_fila;
    private javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
}
